### ISSUE TITLE
Site has not updated since 2022-06-13

### ISSUE THREAD

**Issue by apiology** [geospatialorg/covid19#54]
Will https://covid19.geo-spatial.org/ be supported going forward?

> Date of last update: 13-06-2022 10:43:59

I am writing because this impacted microCOVID.org, which uses your data as part of its site: https://github.com/microCOVID/microCOVID/issues/1476

**Comment by vasile33** [comment]
Hi Vince,

The website is not updated because the government decided to end the daily updates on COVID-19. We are thinking for a solution to maintain the website up, at leas for historic reasons but also working to somehow provide daily data again. Keep you posted.

**Comment by apiology** [comment]
Updates have returned!
