### ISSUE TITLE
Growth rate graph

### ISSUE THREAD

**Issue by ruxandra-valcu** [geospatialorg/covid19#6]
![rata_de_crestere](https://user-images.githubusercontent.com/15108241/77230190-1a166680-6b9b-11ea-914e-997f1b4bef05.png)

Quick example, without showing measures taken
Growth rate is calculated by dividing today's cumulative cases with yesterday's. I would skip the days in which they messed with the reporting mode (flagged in our spreadsheet, Cazuri noi pe zile sheet, Schimbare a modului de raportare = da, also skip the next growth rate after that since yesterday's value is messed up) since it's really important to have a standard 24h period corresponding to each day - unlike in the cumulative cases graph, you don't have the smoothing effect of the cumulative sum.

What this shows us: if we have a horizontal line on this graph or parts of it, that's stable exponential growth . If the fit is best done by multiple horizontal lines on segments of the graph, that's exponential growth that is increasing or decreasing in severity based on external factors e.g measures taken. It'd be useful to have measures taken in this graph as well, just as shown on the cumulative cases fit

**Comment by silviu001** [comment]
Implemented except the 'skip' part as the API doesn't publish the reporting mode changes.

It will be reflected in the next UI version release.
