### ISSUE TITLE
Labelling of cumulative cases vs day graph

### ISSUE THREAD

**Issue by ruxandra-valcu** [geospatialorg/covid19#7]
Pe moment, curbele de fitting sunt etichetate cu "ecuatia dreptei[tipul de curba]". Ar fi mai clar pt useru' neavizat sa fie etichetate drept "Crestere exponentiala/lineara/logaritmica[ecuatia]"

**Comment by silviu001** [comment]
Am eliminat curbele lineara si logaritmica si am modificat eticheta pentru curba exponentiala. 

Modificarile vor fi vizibile in urmatorul release.

Multumim pentru sugestii.
